name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up GitHub Pages
        run: |
          mkdir -p public/COURSE_PRACTICE_QUESTIONS/Testing
          cp -r COURSE_PRACTICE_QUESTIONS/Testing/* public/COURSE_PRACTICE_QUESTIONS/Testing/
          cp -r skulpt-dist-master public/skulpt-dist-master

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true